# Generated by Django 5.1.7 on 2025-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='child_age',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='child age'),
        ),
    ]
