# Generated by Django 5.1.7 on 2025-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_child_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='child_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='child age'),
        ),
    ]
