# Generated by Django 5.1.7 on 2025-05-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='child_name',
            field=models.CharField(blank=True, null=True, verbose_name='child name'),
        ),
    ]
