# Generated by Django 5.1.7 on 2025-05-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_child_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
    ]
