# Generated by Django 5.1.7 on 2025-05-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_delete_subscription_remove_application_message'),
        ('courses', '0003_delete_coursesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.course', verbose_name='course'),
            preserve_default=False,
        ),
    ]
