# Generated by Django 5.1.7 on 2025-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_delete_contactrequest_alter_application_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='study_type',
            field=models.CharField(choices=[('school', 'Занятия в клубе'), ('online', 'Онлайн-занятия')], default='school', max_length=10, verbose_name='Тип занятий'),
        ),
    ]
