# Generated by Django 5.1.7 on 2025-05-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSubscription',
        ),
    ]
